# Generated by Django 5.1.1 on 2024-10-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskmodel_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='assignee',
            new_name='executor',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='title',
            new_name='name',
        ),
    ]
